<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title><?= $title;?></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    </head>
    <body>
    
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container">
            <div class="row">
                <a class="navbar-brand d-flex align-items-center" href="<?= url();?>">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="navbar-brand d-flex align-items-center" href="<?= url("produtos/");?>"> Produtos    </a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand d-flex align-items-center" href="<?= url("vendas/");?>">   Vendas      </a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand d-flex align-items-center" href="<?= url("tipos/");?>">   Tipos      </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main class="main_content">
            <?= $v->section("content");?>
        </main>
        <footer class="text-muted">
            <div class="container">
                <center><p> <?= SITE;?> - Todos os Direitos Reservados</p></center>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </body>
</html>