<?php $v->layout("..\_theme");?>
<div class="container">
    <div class="row">
        <div class="col-md-12 order-md-1">
            <h5>Produtos <a href="<?= url("produtos/inserir");?>" class="btn btn-primary active" role="button" aria-pressed="true">Inserir</a></h5>
            <?php if($produtos):?>
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                        <th scope="col">#</th>
                        <th scope="col">Descrição</th>
                        <th scope="col">Tipo</th>
                        <th scope="col">Quantidade</th>
                        <th scope="col">Valor</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($produtos as $produto):?>
                            <tr>
                                <th scope="row"><?= $produto->id;?></th>
                                <td><?= $produto->descricao;?></td>
                                <td><?= $produto->tipo_id;?></td>
                                <td><?= $produto->quantidade;?></td>
                                <td><?= $produto->valor;?></td>
                            </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            <?php endif;?>
        </div>
    </div>
</div>